TOP = ..
include $(TOP)/configure/CONFIG
DIRS += src
DIRS += record
DIRS += pvCopy
DIRS += exampleCounter
DIRS += exampleServer
DIRS += examplePVADoubleArrayGet
DIRS += arrayPerformance
DIRS += v3IOC
include $(TOP)/configure/RULES_DIRS

