# This is a Makefile fragment, see ../Makefile

SRC_DIRS += $(PVDATABASE_SRC)/special

DBD += pvdbcrTraceRecordRegister.dbd
DBD += pvdbcrRemoveRecordRegister.dbd
DBD += pvdbcrAddRecordRegister.dbd
DBD += pvdbcrProcessRecordRegister.dbd
DBD += pvdbcrScalarRegister.dbd
DBD += pvdbcrScalarArrayRegister.dbd
DBD += pvdbSpecialRegister.dbd

LIBSRCS += pvdbcrScalarRegister.cpp
LIBSRCS += pvdbcrScalarArrayRegister.cpp
LIBSRCS += pvdbcrTraceRecordRegister.cpp
LIBSRCS += pvdbcrRemoveRecordRegister.cpp
LIBSRCS += pvdbcrAddRecordRegister.cpp
LIBSRCS += pvdbcrProcessRecordRegister.cpp

