# This is a Makefile fragment, see ../Makefile

SRC_DIRS += $(PVDATABASE_SRC)/special

LIBSRCS += traceRecord.cpp
LIBSRCS += removeRecord.cpp
LIBSRCS += numericRecord.cpp

DBD += traceRecordRegister.dbd
DBD += removeRecordRegister.dbd
DBD += numericRecordRegister.dbd

LIBSRCS += traceRecordRegister.cpp
LIBSRCS += removeRecordRegister.cpp
LIBSRCS += numericRecordRegister.cpp
