# This is a Makefile fragment, see ../Makefile

SRC_DIRS += $(PVDATABASE_SRC)/special

DBD += traceRecordRegister.dbd
DBD += removeRecordRegister.dbd
DBD += addRecordRegister.dbd
DBD += processRecordRegister.dbd

LIBSRCS += traceRecordRegister.cpp
LIBSRCS += removeRecordRegister.cpp
LIBSRCS += addRecordRegister.cpp
LIBSRCS += processRecordRegister.cpp

DBD += pvdbcrTraceRecordRegister.dbd
DBD += pvdbcrRemoveRecordRegister.dbd
DBD += pvdbcrAddRecordRegister.dbd
DBD += pvdbcrProcessRecordRegister.dbd
DBD += pvdbcrScalarRegister.dbd
DBD += pvdbcrScalarArrayRegister.dbd
DBD += pvdbSpecialRegister.dbd

LIBSRCS += pvdbcrTraceRecordRegister.cpp
LIBSRCS += pvdbcrRemoveRecordRegister.cpp
LIBSRCS += pvdbcrAddRecordRegister.cpp
LIBSRCS += pvdbcrProcessRecordRegister.cpp
LIBSRCS += pvdbcrScalarRegister.cpp
LIBSRCS += pvdbcrScalarArrayRegister.cpp

