TOP=../..

include $(TOP)/configure/CONFIG

#PROD_HOST += testPVCopy
#testPVCopy_SRCS += testPVCopy.cpp
#testPVCopy_LIBS += pvDatabase pvAccess pvData Com

PROD_HOST += testPVRecord
testPVRecord_SRCS += testPVRecord.cpp
testPVRecord_LIBS += pvDatabase pvAccess pvData Com

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

