TOP=../..

include $(TOP)/configure/CONFIG

PROD_HOST += exampleRecord
exampleRecord_SRCS += exampleRecord.cpp
exampleRecord_SRCS += exampleRecordMain.cpp
exampleRecord_LIBS += pvDatabase pvAccess pvData Com

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

