TOP=../..

include $(TOP)/configure/CONFIG

PROD_HOST += testExampleRecord
testExampleRecord_SRCS += testExampleRecordMain.cpp
testExampleRecord_LIBS += pvDatabase pvAccess pvData Com


include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

