TOP=../..

include $(TOP)/configure/CONFIG

PROD_HOST += testRecord
testRecord_SRCS += testRecord.cpp
testRecord_SRCS += testRecordMain.cpp
testRecord_LIBS += pvDatabase pvAccess pvData Com

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

