TOP=../..

include $(TOP)/configure/CONFIG

PROD_HOST += examplePVADoubleArrayGetMain
examplePVADoubleArrayGetMain_SRCS += examplePVADoubleArrayGetMain.cpp
examplePVADoubleArrayGetMain_LIBS += pvDatabase pvAccess pvData Com
examplePVADoubleArrayGetMain_LIBS += pvDatabaseExample


include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

