TOP=../..

include $(TOP)/configure/CONFIG

PROD_HOST += exampleCounterMain
exampleCounterMain_SRCS += exampleCounterMain.cpp
exampleCounterMain_LIBS += pvDatabase pvAccess pvData Com


include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

