# This is a Makefile fragment, see ../Makefile

SRC_DIRS += $(PVDATABASE_SRC)/pvAccess

INC += channelProviderLocal.h
INC += pvCopy.h
INC += monitorAlgorithm.h

DBD += registerChannelProviderLocal.dbd

LIBSRCS += channelProviderLocal.cpp
LIBSRCS += pvCopy.cpp
LIBSRCS += monitorFactory.cpp
LIBSRCS += channelLocal.cpp
LIBSRCS += registerChannelProviderLocal.cpp
