TOP=../..

include $(TOP)/configure/CONFIG

PROD_HOST += testExampleServer
testExampleServer_SRCS += testExampleServerMain.cpp
testExampleServer_LIBS += pvDatabase pvAccess pvData Com

PROD_HOST += exampleCounter
exampleCounter_SRCS += exampleCounterMain.cpp
exampleCounter_LIBS += pvDatabase pvAccess pvData Com


include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

